<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- Use published SDK from NuGet (default) -->
 
  <ItemGroup>
    <PackageReference Include="Nimbbl.Sdk.Rest" Version="1.3.5-rc5" />
  </ItemGroup>



  <!-- Use local SDK source (uncomment to use local SDK instead of published package) -->
     <!--
  <ItemGroup>
    <ProjectReference Include="..\Nimbbl.Sdk.Rest\Nimbbl.Sdk.Rest.csproj" />
  </ItemGroup>
    -->
</Project>

